version: "3"

services:
  dev:
    image: node:10
    volumes:
      - ./:/app/
      - next_build:/app/.next
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "3000"
    command: yarn dev

volumes:
  node_modules:
  next_build:

